services:
  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - "11434:11434"
    deploy:
      # Just for local testing
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G

  code-review-server:
    image: docker.io/superstep/code-review-server:0.0.6
    container_name: code-review-server
    environment:
      - GITEA_BASE_URL=http://gitea:3000
      - GITEA_TOKEN=ffcd50d94a40abd4c2c93a93a65edddfdf462ba1
      - GITEA_OWNER=gitea_admin
      - GITEA_REPOSITORY=example
      - AI_PROVIDER=ollama
      - AI_READ_TIMEOUT_SEC=600
#      - GEMINI_TOKEN=our-gemini-api-token
#      - GEMINI_MODEL=gemini-2.0-flash
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen2.5-coder:3b
      - GIT_WORK_DIRECTORY=/git
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .git/:/git/
    depends_on:
      - gitea
      - ollama
  gitea:
    image: docker.gitea.com/gitea:1.23.7
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "7999:22"
    depends_on:
        - db-gitea
  db-gitea:
    image: docker.io/library/postgres:14
    restart: always
    environment:
        - POSTGRES_USER=gitea
        - POSTGRES_PASSWORD=gitea
        - POSTGRES_DB=gitea
    volumes:
        - ./postgres:/var/lib/postgresql/datacu

  db-indexer:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/home/postgres/pgdata/data
    command: [ "-c", "ai.ollama_host=http://host.docker.internal:11434" ]

  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:latest
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://postgres:postgres@db-indexer:5432/postgres
      OLLAMA_HOST: http://host.docker.internal:11434
    command: [ "--poll-interval", "5s", "--log-level", "DEBUG" ]
    depends_on:
      - db-indexer

volumes:
  data: