spring:
  application:
    name: code-review-server
  quartz:
    job-store-type: memory

# Job Configuration
app:
  jobs:
    pull-request-fetch:
      enabled: true
      interval-in-seconds: 60
      bot-name: '@bot'
    review-process:
      enabled: true
      interval-in-seconds: 10
    review-result-process:
      enabled: true
      interval-in-seconds: 10

# AI Provider Configuration
ai:
  provider: gemini  # Options: ollama, gemini

# Ollama Configuration
ollama:
  baseUrl: http://localhost:11434
  model: qwen2.5-coder:3b
  temperature: 0.7
  maxTokens: 4096

# Gemini Configuration
gemini:
  # token: your-gemini-api-token
  model: gemini-2.0-flash

gitea:
  baseUrl: http://localhost:3000
  token: ffcd50d94a40abd4c2c93a93a65edddfdf462ba1
  owner: gitea_admin
  repository: example

logging:
  level:
    dev.gordeev.server: DEBUG

# Git diff configuration
git:
  work-directory: tmp/git

