spring:
  application:
    name: code-review-server
  quartz:
    job-store-type: memory
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Job Configuration
app:
  jobs:
    pull-request-fetch:
      enabled: true
      interval-in-seconds: 60
      bot-name: '@bot'
    review-process:
      enabled: true
      interval-in-seconds: 10
    review-result-process:
      enabled: true
      interval-in-seconds: 10
    repository-indexer:
      enabled: true
      intervalInSeconds: 300

# AI Provider Configuration
ai:
  provider: ollama  # Options: ollama, gemini
  readTimeoutSec: 120
  review:
    prompt:
      template: |
        Ты проводишь ревью кода. Проверь следующий код на наличие ошибок, недочетов и лучших практик.
        Не обясняй что тут происходит, просто найти проблемные места ии недочеты.
        
        Pull Request: ${title}
        
        Вот изменения:
        ${diff}
        
        Пожалуйста, дай мне ответ на русском языке.
        1. Основные проблемы или вопросы
        2. Стиль и рекомендации по лучшим практикам
        3. Замечания по безопасности, если они применимы

        ${reviewComment}

        Особенно учти контекст репозитория ниже:
        ${context}

# Ollama Configuration
ollama:
  baseUrl: http://localhost:11434
  model: qwen2.5-coder:3b
  temperature: 0.7
  maxTokens: 4096

# Gemini Configuration
gemini:
  # token: your-gemini-api-token
  model: gemini-2.0-flash

gitea:
  baseUrl: http://localhost:3000
  token: 037c312f20f438ab06f55a6259d08c073f816917 # gitea_admin:gitea_admin
  owner: gitea_admin
  repository: spring-petclinic

# Git diff configuration
git:
  work-directory: /tmp/git

# Indexer Configuration
indexer:
  repositories:
    - name: "spring-petclinic"
      url: https://github.com/spring-projects/spring-petclinic.git
  clone:
    base-path: /tmp/git

logging:
  level:
    dev.gordeev.server: DEBUG