spring:
  application:
    name: code-review-server
  quartz:
    job-store-type: memory
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

# Job Configuration
app:
  jobs:
    pull-request-fetch:
      enabled: true
      interval-in-seconds: 10
      bot-name: '@bot'
    review-process:
      enabled: true
      interval-in-seconds: 10
    review-result-process:
      enabled: true
      interval-in-seconds: 10

# AI Provider Configuration
ai:
  provider: gemini  # Options: ollama, gemini

# Ollama Configuration
ollama:
  baseUrl: http://localhost:11434
  model: qwen2.5-coder:3b
  temperature: 0.7
  maxTokens: 4096

# Gemini Configuration
gemini:
  # token: your-gemini-api-token
  model: gemini-2.0-flash

# Bitbucket Configuration
bitbucket:
  baseUrl: http://localhost:7990/rest/api/1.0
#  token: your-bitbucket-access-token
#  certificatePath: path
#  certificatePassword: your-password
  project: SWTR
  repository: swtr-core

logging:
  level:
    dev.gordeev.server: DEBUG

# Git diff configuration
git:
  work-directory: tmp/git

